### ISSUE TITLE
Why admin login?

### ISSUE THREAD

**Issue by vergissberlin** [Rigidflame/firebase-login#1]
**Hi!**

Why did you decide to use the admin login? 
This is a security risk under certain circumstances.

regards,
André

**Comment by abeisgoat** [comment]
This is a wrapper for the official auth system used by the Firebase Dashboard / Forge. When you visit your Firebase in the browser, you are first given an auth token, which can then be used to fetch the Firebase secret. 

At this point, you could generate a non-admin token with the secret, but you've already fetched the secret and there is no getting around that, so the security risk is there regardless.
